apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ecommerce-virtualservice
  namespace: ecommerce
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: /products
    fault:
      delay:
        percentage:
          value: 50
        fixedDelay: 2s
    retries:
      attempts: 3
      perTryTimeout: 2s
    timeout: 5s
    route:
    - destination:
        host: product-service
        subset: v1
        port:
          number: 80
      weight: 90
    - destination:
        host: product-service
        subset: v2
        port:
          number: 80
      weight: 10
