apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::527769887303:role/KarpenterControllerRole-gitops-eks