apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: 527769887303.dkr.ecr.us-east-1.amazonaws.com/my-web-app:c174e8c5c7e0de920be28ff80a6c8312a902eddc
        ports:
        - containerPort: 80