apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: 527769887303.dkr.ecr.us-east-1.amazonaws.com/my-web-app:4235a425f00ceed26f71fedd3a5bffa7285ccd12
        ports:
        - containerPort: 80