apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: 527769887303.dkr.ecr.us-east-1.amazonaws.com/my-web-app:07b2666ce6a72a6d8dc5272b00a160fe6df7354a
        ports:
        - containerPort: 80